services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PORTS: 5434:5434
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  ###> doctrine/doctrine-bundle ###
